# Generated by Django 4.2.20 on 2025-04-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idconsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaconsulta', models.DateField(auto_now=True, verbose_name='Fecha de consulta')),
                ('horaconsulta', models.TimeField(auto_now=True, verbose_name='Hora consulta')),
                ('precioconsulta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('tipo', models.CharField(choices=[('Lesion', 'Lesion'), ('Patologia', 'Patologia')], max_length=9, verbose_name='Tipo')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fechacreacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta', models.AutoField(primary_key=True, serialize=False)),
                ('fechareceta', models.DateField(auto_now=True, verbose_name='Fecha de receta')),
                ('medicamento', models.CharField(max_length=500, verbose_name='Medicamento')),
                ('dosis', models.CharField(max_length=500, verbose_name='Dosis')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duracion')),
                ('indicaciones', models.CharField(max_length=500, verbose_name='Indicaciones')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.paciente'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(primary_key=True, serialize=False)),
                ('fechacita', models.DateField(verbose_name='Fecha de cita')),
                ('horacita', models.CharField(choices=[('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('13', '01:00 - 02:00'), ('14', '02:00 - 03:00'), ('15', '03:00 - 04:00'), ('16', '04:00 - 05:00'), ('17', '05:00 - 06:00')], max_length=11, verbose_name='Hora cita')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.paciente')),
            ],
        ),
    ]
