# Generated by Django 4.2.20 on 2025-05-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fechaconsulta',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de consulta'),
        ),
    ]
