# Generated by Django 4.2.20 on 2025-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_alter_consulta_fechaconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('idejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=300, verbose_name='Categoria')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='ejercicios/', verbose_name='PDF')),
                ('subcategoria', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subcategoria')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('semana', models.PositiveIntegerField(verbose_name='Semana')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='ejercicios/', verbose_name='Imagenes')),
            ],
        ),
    ]
