# Generated by Django 4.2.20 on 2025-05-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_ejercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(max_length=300, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.CharField(max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='ejercicios/pdfs/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Subcategoría'),
        ),
    ]
