# Generated by Django 4.2.20 on 2025-05-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_remove_ejercicio_imagenes_ejercicio_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(max_length=300, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.CharField(max_length=300, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='ejercicios/', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Subcategoria'),
        ),
        migrations.CreateModel(
            name='ImagenEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ejercicios/imagenes/')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='gestor.ejercicio')),
            ],
        ),
    ]
