# Generated by Django 4.2.20 on 2025-07-14 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0005_remove_ejercicio_imagen_alter_ejercicio_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observaciones',
            field=models.CharField(max_length=500, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='ejercicios/pdf', verbose_name='PDF'),
        ),
    ]
