# Generated by Django 4.2 on 2025-07-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_alter_paciente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='horacita',
            field=models.IntegerField(choices=[(8, '8:00 - 9:00'), (9, '9:00 - 10:00'), (10, '10:00 - 11:00'), (11, '11:00 - 12:00'), (13, '01:00 - 02:00'), (14, '02:00 - 03:00'), (15, '03:00 - 04:00'), (16, '04:00 - 05:00'), (17, '05:00 - 06:00')], verbose_name='Hora cita'),
        ),
    ]
